# Generated by Django 5.0.1 on 2024-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.CharField(max_length=100)),
                ('urlId', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
