# Generated by Django 5.0.1 on 2024-07-21 18:56

import urlShortner.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urlId',
            field=urlShortner.models.URLID(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
