# Generated by Django 5.0.1 on 2024-07-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortner', '0002_alter_url_urlid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
